import * as React from "react";

export interface DocSection {
  id: string;
  label: string;
  title: string;
  group: "getting-started" | "core-concepts" | "features" | "reference";
  template: "A" | "B" | "C" | "D";
  description: string; // One sentence (max 18 words) explaining what it is.
  problem: string[]; // Block 4: The Problem
  solutionText: string; // Block 5: PW-Core Solution
  code: string | React.ReactNode; // Block 6: Interactive Example
  codeFilename: string;
  results: string[]; // Block 7: Visual Result
  whyItMatters: string[]; // Block 8: Why this matters
  useThisIf: string[]; // Block 9: You'll use this if...
  avoidIf?: string[]; // Block 10: Avoid if (optional)
  prevLink?: { id: string; label: string };
  nextLink?: { id: string; label: string };
  onLearnMoreKey: string;
  illustration?: React.ReactNode | null;
  rightTitle?: string;
  rightPoints?: string[];
}

export const docsSectionsData: DocSection[] = [
  {
    id: "installation",
    label: "GETTING STARTED",
    title: "Installation",
    group: "getting-started",
    template: "A",
    description: "Install pw-core package and bootstrap your Playwright project structure.",
    onLearnMoreKey: "installation",
    problem: [
      "Manual setup configurations",
      "Scattered directory layouts",
      "No standardized entrypoints"
    ],
    solutionText: "Add pw-core to your project and run init to configure folders and configs.",
    codeFilename: "Terminal",
    code: "npm install pw-core\nnpx pw-core init",
    results: [
      "✓ Package installed to package.json",
      "✓ Config file created in root",
      "✓ Directories configured"
    ],
    whyItMatters: [
      "Saves initial setup time",
      "Establishes clean file patterns",
      "No complex manual config"
    ],
    useThisIf: [
      "Integrating with existing Playwright repos",
      "Setting up fresh workspaces"
    ],
    nextLink: { id: "your-first-test", label: "Your First Test" }
  },
  {
    id: "your-first-test",
    label: "GETTING STARTED",
    title: "Your First Test",
    group: "getting-started",
    template: "A",
    description: "Write a test using your registry and run it with the Playwright CLI.",
    onLearnMoreKey: "first-test",
    problem: [
      "Scattered import lists in specs",
      "Setting up custom page contexts",
      "Writing manual fixture wiring code"
    ],
    solutionText: "Create a page registry, write your E2E test block, and run standard Playwright command.",
    codeFilename: "login.test.ts",
    code: `// 1. Create registry\nconst test = createPageRegistry({\n  login: { url: "/login", button: ["Sign In"] }\n});\n\n// 2. Write test\ntest("Login", async ({ login }) => {\n  await login.goto();\n  await login.click("Sign In");\n});\n\n// 3. Run command\nnpx playwright test`,
    results: [
      "✓ Passing test run successfully",
      "✓ Auto-wired page selectors active",
      "✓ Zero boilerplates in spec file"
    ],
    whyItMatters: [
      "Instant script execution",
      "No complex wrapper imports",
      "Fast feedback loop"
    ],
    useThisIf: [
      "Running your first test spec",
      "Validating basic setup"
    ],
    prevLink: { id: "installation", label: "Installation" },
    nextLink: { id: "page-registry", label: "Page Registry" }
  },
  {
    id: "page-registry",
    label: "CORE CONCEPTS",
    title: "Page Registry",
    group: "core-concepts",
    template: "A",
    description: "Define one application screen with a single registry object. PW-Core generates typed pages, fixtures, and APIs from this configuration.",
    onLearnMoreKey: "registry",
    problem: [], solutionText: "", codeFilename: "", code: "", results: [], whyItMatters: [], useThisIf: [],
    prevLink: { id: "your-first-test", label: "Your First Test" },
    nextLink: { id: "extend-fixtures", label: "Extend Fixtures" }
  },
  {
    id: "extend-fixtures",
    label: "CORE CONCEPTS",
    title: "Extend Fixtures",
    group: "core-concepts",
    template: "A",
    description: "Customize, replace, or extend the fixtures automatically generated by PW-Core.",
    onLearnMoreKey: "typed-page",
    problem: [], solutionText: "", codeFilename: "", code: "", results: [], whyItMatters: [], useThisIf: [],
    prevLink: { id: "page-registry", label: "Page Registry" },
    nextLink: { id: "test-runtime", label: "Test Runtime" }
  },
  {
    id: "test-runtime",
    label: "CORE CONCEPTS",
    title: "Test Runtime",
    group: "core-concepts",
    template: "B",
    description: "Create a typed Playwright-compatible test from your page registry.",
    onLearnMoreKey: "runtime",
    problem: [], solutionText: "", codeFilename: "", code: "", results: [], whyItMatters: [], useThisIf: [],
    prevLink: { id: "extend-fixtures", label: "Extend Fixtures" },
    nextLink: { id: "pw-core-codegen", label: "PW-Core Codegen" }
  },
  {
    id: "pw-core-codegen",
    label: "FEATURES",
    title: "PW-Core Codegen",
    group: "features",
    template: "C",
    description: "Record interactions once. PW-Core automatically keeps your page registries, page objects, and tests synchronized.",
    onLearnMoreKey: "codegen",
    problem: [
      "Looking up CSS locators in DevTools",
      "Slow initial test script authoring",
      "Incorrect accessibility role usage"
    ],
    solutionText: "Launch our interactive browser recorder. Interacting with UI elements updates your configuration files.",
    codeFilename: "Terminal",
    code: "npx pw-core codegen",
    results: [
      "✓ Element config keys auto-created",
      "✓ Test specs output instantly",
      "✓ Clean accessibility roles set"
    ],
    whyItMatters: [
      "Ultra-fast test authoring",
      "Eliminates selector mistakes",
      "Standardizes elements layout"
    ],
    useThisIf: [
      "Writing fresh test cases",
      "Quickly generating page configurations"
    ],
    prevLink: { id: "test-runtime", label: "Test Runtime" },
    nextLink: { id: "internal-locators", label: "Internal Locators" }
  },
  {
    id: "internal-locators",
    label: "FEATURES",
    title: "Internal Locators",
    group: "features",
    template: "C",
    description: "Define Playwright semantic locators once in your page registry and use simple registry keys throughout your tests.",
    onLearnMoreKey: "locators",
    problem: [
      "Verbose page.locator queries in tests",
      "Fragile XPath/CSS strings inside specs",
      "Broken tests on class selector tweaks"
    ],
    solutionText: "Call click, fill, or verify with target registry keys. PW-Core resolves elements behind the scenes.",
    codeFilename: "login.test.ts",
    code: `// call by key instead of writing locators\nawait login.click("Sign In");`,
    results: [
      "✓ Mapped to A11y role at runtime",
      "✓ No raw locator strings in specs",
      "✓ Resilient test validations"
    ],
    whyItMatters: [
      "Resilient E2E specs",
      "Encourages accessibility audits",
      "No locator details in test files"
    ],
    useThisIf: [
      "Writing new action blocks",
      "Ensuring clean, robust locators"
    ],
    prevLink: { id: "pw-core-codegen", label: "PW-Core Codegen" },
    nextLink: { id: "dynamic-locators", label: "Dynamic Locators" }
  },
  {
    id: "dynamic-locators",
    label: "FEATURES",
    title: "Dynamic Locators",
    group: "features",
    template: "C",
    description: "Define locator templates once in pageConfig. PW-Core generates typed locator keys automatically.",
    onLearnMoreKey: "dynamic",
    problem: [
      "Selecting table rows with specific text",
      "Messy string concatenations in E2E specs",
      "Fragile dynamic target queries"
    ],
    solutionText: "Define placeholders in your locator string and pass data arguments in test calls.",
    codeFilename: "users.test.ts",
    code: `// Config template: userRow: "user-row-{id}"\n\nawait users.click("userRow", { id: "101" });`,
    results: [
      "✓ Dynamic parameters injected",
      "✓ Type-safe arguments verified",
      "✓ Easy table row targeting"
    ],
    whyItMatters: [
      "Clean dynamic actions",
      "Stops locator typos in tests",
      "Flexible table and list selectors"
    ],
    useThisIf: [
      "Targeting elements in lists or grids",
      "Passing query variables to locators"
    ],
    prevLink: { id: "internal-locators", label: "Internal Locators" },
    nextLink: { id: "chain-locators", label: "Chain Locators" }
  },
  {
    id: "chain-locators",
    label: "FEATURES",
    title: "Chain Locators",
    group: "features",
    template: "C",
    description: "Access nested registry locators with typed dot notation using chain().",
    onLearnMoreKey: "chain-locators",
    problem: [], solutionText: "", codeFilename: "", code: "", results: [], whyItMatters: [], useThisIf: [],
    prevLink: { id: "dynamic-locators", label: "Dynamic Locators" },
    nextLink: { id: "auto-steps", label: "Auto Steps" }
  },
  {
    id: "auto-steps",
    label: "FEATURES",
    title: "Auto Steps",
    group: "features",
    template: "C",
    description: "Every page method automatically becomes a readable Playwright report step.",
    onLearnMoreKey: "autosteps",
    problem: [
      "Writing manual test.step wraps in helpers",
      "Polluted helper code files",
      "Non-descriptive E2E traces in reports"
    ],
    solutionText: "PW-Core wraps method operations so execution blocks display automatically inside Playwright reports.",
    codeFilename: "login.test.ts",
    code: `// Test code:\nawait login.login();`,
    results: [
      "✓ Action details visible in steps",
      "✓ Trace reports structured",
      "✓ Zero extra coding required"
    ],
    whyItMatters: [
      "Saves manual step coding time",
      "Readable stakeholder reports",
      "Quick E2E trace debugging"
    ],
    useThisIf: [
      "Running tests in CI systems",
      "Generating report trace files"
    ],
    prevLink: { id: "chain-locators", label: "Chain Locators" },
    nextLink: { id: "secret-masking", label: "Secret Masking" }
  },
  {
    id: "secret-masking",
    label: "FEATURES",
    title: "Secret Masking",
    group: "features",
    template: "C",
    description: "Automatically masks passwords and secrets in Playwright reports, traces, and execution logs.",
    onLearnMoreKey: "masking",
    problem: [
      "Passwords exposed in report steps",
      "Secrets visible inside trace viewer",
      "Compliance and audit failures"
    ],
    solutionText: "PW-Core detects password field interactions and replaces captured values with ******** across all generated reports automatically.",
    codeFilename: "login.test.ts",
    code: `// password inputs are masked automatically\nawait login.fill("password", process.env.DB_PASSWORD);`,
    results: [
      "✓ Credentials masked inside traces",
      "✓ Secured HTML execution logs",
      "✓ Zero custom setup needed"
    ],
    whyItMatters: [
      "Prevents password leaks in logs",
      "Ensures pipeline compliance",
      "Always on by default"
    ],
    useThisIf: [
      "Filling credential input forms",
      "Publishing public build traces"
    ],
    prevLink: { id: "auto-steps", label: "Auto Steps" },
    nextLink: { id: "cli", label: "CLI" }
  },
  {
    id: "cli",
    label: "REFERENCE",
    title: "CLI",
    group: "reference",
    template: "D",
    description: "Initialize, validate, and record configurations via terminal commands.",
    onLearnMoreKey: "cli",
    problem: [],
    solutionText: "",
    codeFilename: "",
    code: "",
    results: [],
    whyItMatters: [],
    useThisIf: [],
    prevLink: { id: "secret-masking", label: "Secret Masking" },
    nextLink: { id: "releases", label: "Releases" }
  },
  {
    id: "releases",
    label: "REFERENCE",
    title: "Releases",
    group: "reference",
    template: "D",
    description: "Release history, changelogs, and upgrade guides for pw-core.",
    onLearnMoreKey: "releases",
    problem: [],
    solutionText: "",
    codeFilename: "",
    code: "",
    results: [],
    whyItMatters: [],
    useThisIf: [],
    prevLink: { id: "cli", label: "CLI" }
  }
];

export const docsNavigation = docsSectionsData;
